site:
  title: "我的静态"
  description: "欢迎来到我的个人网站，分享技术文章和心得体会"
  author: "您的名字"
  baseUrl: "http://localhost:3000"
  language: "zh-CN"
  keywords:
    - "技术博客"
    - "编程"
    - "Web开发"

paths:
  content: "./content"
  templates: "./templates"
  output: "./output"
  static: "./static"

markdown:
  breaks: true
  gfm: true
  headerIds: true

server:
  port: 3000
  open: true
  watch: true

build:
  cleanOutput: true
  copyStatic: true
  generateSitemap: true
  generateHomepage: true

features:
  comments: true
  search: false
  darkMode: true

custom:
  googleAnalytics: "UA-XXXXX-Y"
  disqusShortname: "yourshortname"
  copyright: "© 2023 我的网站. 保留所有权利."